# Generated by Django 5.2.7 on 2025-10-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nume_actor', models.CharField(max_length=100)),
                ('prenume_actor', models.CharField(max_length=100)),
                ('an_nastere_actor', models.IntegerField(blank=True, null=True)),
                ('sex_actor', models.CharField(max_length=1)),
                ('nationalitate_actor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('an_aparitie', models.IntegerField(blank=True, null=True)),
                ('nume_film', models.CharField(max_length=255)),
                ('cost_prod', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_brut', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('varsta_necesara', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('durata', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id_gen', models.AutoField(primary_key=True, serialize=False)),
                ('nume_gen', models.CharField(max_length=100, unique=True)),
                ('descriere_gen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regizor',
            fields=[
                ('id_regizor', models.AutoField(primary_key=True, serialize=False)),
                ('nume_regizor', models.CharField(max_length=100)),
                ('prenume_regizor', models.CharField(max_length=100)),
                ('an_nastere_regizor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id_studio', models.AutoField(primary_key=True, serialize=False)),
                ('nume_studio', models.CharField(max_length=255, unique=True)),
                ('an_infintare', models.IntegerField(blank=True, null=True)),
                ('sediu_studio', models.CharField(blank=True, max_length=255, null=True)),
                ('tara_provenienta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id_utilizator', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola_hash', models.CharField(max_length=255)),
                ('data_inregistrare', models.DateTimeField(auto_now_add=True)),
                ('varsta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('nume_comentariu', models.CharField(blank=True, max_length=255, null=True)),
                ('descriere_comentariu', models.TextField(blank=True, null=True)),
                ('rating_comentariu', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
                ('id_utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizator')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='id_regizor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.regizor'),
        ),
        migrations.AddField(
            model_name='film',
            name='id_studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studio'),
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=255, null=True)),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
            options={
                'unique_together': {('id_film', 'id_actor')},
            },
        ),
        migrations.CreateModel(
            name='FilmGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
                ('id_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gen')),
            ],
            options={
                'unique_together': {('id_film', 'id_gen')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackReactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_actiune', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
                ('id_utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizator')),
            ],
            options={
                'unique_together': {('id_feedback', 'id_utilizator', 'tip_actiune')},
            },
        ),
    ]
